item2item_template = [
    "Can you recommend me some items similar to {}?",
    "I have played this game: {} and find it interesting. Are there other games similar to this one?",
    "Looking for games like this: {}. Any suggestions?",
    "I enjoyed this item: {}, can you recommend anything similar?",
    "Any recommendations for games related to {}?",
    "Find me more games like {} please.",
    "Which games share similarities with this game? {}",
    "Just played this game: {}, and I'm craving more with the same feel. Any ideas?",
    "{} was so much fun! What other similar games would you recommend?",
    "Are there any other games with the same feel as this game? {}",
    "Games similar to this one {}",
    "I'm looking for games similar to {}",
    "Recommend games similar to this game: {}.",
    "Similar games to {}.",
    "Games like {}.",
    "Items similar to {}.",
    "Items like {}.",
    "Recommend items similar to this one: {}.",
    "Related games to {}.",
]
