query2item_template = [
    "{}",
    "I want to find some games with several features: {}.", 
    "Recommend games for a user who likes games that have these features {}.", 
    "I prefer games with the following type: {}, can you recommend some for me?",
    "Recommend an item that meets the following requirements: {}.",
    "I'm looking for games that include these elements: {}.",
    "Suggest some games for someone who enjoys features like {}.",
    "I have a taste for this kind of games {}, what do you recommend?",
    "Find me a game that matches these criteria: {}.",
    "I'm in search of games with these characteristics: {}.",
    "What games can you suggest that offer these features? {}",
    "I'd like to try games that incorporate {}. Any recommendations?",
    "Help me find games with the following attributes: {}.",
    "Can you recommend games that focus on elements like {}",
    "I enjoy games with {}, can you suggest any?",
    "I'm interested in games that provide elements like {}. What are my options?",
    "What are some good games that emphasize {}?",
    "I'd love to discover games that have {}. Any suggestions?",
    "I'm a fan of this style games: {}. Can you offer some recommendations?",
    "Looking for game suggestions with qualities such as {}",
    "I'm curious about games that highlight {}. What can you recommend?",
    "Games containing {}.",
    "I want to find games featuring {}.",
    "Recommend games with {}.",
    "I'm looking for games that have {}.",
    "I'm interested in games that include {}.",
    "{} are features I'm looking for.",
    "query: {}",
    "Search for games with {}.",
    "Search for {}",
]
