user2item_template = [
    "Asset have the following failure locations: {}.",
    "Recommend an failure location based on other failure locations: {}.",
    "Asset have several failures locations before: {}. Can you recommend other failure locations for given asset?",
    "{} are failure locations I have just discovered, are there any other failure location suitable for given asset?",
    "Given the following failure locations {}, predict next possible failure locations to be analyzed?",
    "Here are the failure locations an asset has experienced {}. What to recommend next?",
    "Find a failure locations for me based on these previous failure locations: {}.",
    "I've observed these failure locations before: {}. What other failure locations should I find?",
    "Observed failure locations list: {}. Suggest a new failure location.",
    "Asset's failure location history includes: {}. What failure locations should be observed next?",
    "These are the failure locations asset have experienced: {}. Offer some new recommendations.",
    "Asset's failure location history: {}. Find a suitable failure locations.",
    "Observed these failure location: {}. What's a failure location to check next?",
    "Considering asset's previous failure locations {}, what would you recommend?",
    "Asset's background failure location includes: {}. Any recommendations?",
    "failure location Asset's has experienced before: {}. What are the other failure locations?",
    "Asset's failure location history: {}. Can you suggest a new?",
    "Check out Asset's failure location history: {}. What failure locations do you recommend?",
    "Failure locations: {}",
    "Asset has experienced {}.",
    "Experienced failure locations: {}.",
    "Played games: {}. Recommend a new game for me.",
    "I've played these games: {}.",
    "{} are games I've played. Any recommendations?",
    "History interactions include: {}.",
]
