user2item_template = [
    "Asset have the following failure locations: {}.",
    "Recommend an failure location based on other failure locations: {}.",
    "Asset have several failures locations before: {}. Can you recommend other failure locations for given asset?",
    "{} are failure locations I have just discovered, are there any other failure location suitable for given asset?",
    "Given the following failure locations {}, predict next possible failure locations to be analyzed?",
    "Here are the failure locations an asset has experienced {}. What to recommend next?",
    "Find a failure locations for me based on these previous failure locations: {}.",
    "I've played these games before: {}. What other games should I try?",
    "Played games list: {}. Suggest a new game for me to play.",
    "My gaming history includes: {}. What game should I play next?",
    "These are the games I've experienced: {}. Offer some new recommendations.",
    "My game history: {}. Find a suitable game for me.",
    "Played these games: {}. What's a good game to try next?",
    "Considering my previous games {}, what would you recommend?",
    "My game background includes: {}. Any recommendations?",
    "Games I've played before: {}. What should I play now?",
    "Played and enjoyed these games: {}. What's next?",
    "Here's my gaming history: {}. Can you suggest a new game?",
    "Check out my game history {}. What game do you recommend?",
    "Histories: {}",
    "I have played {}.",
    "Enjoyed games: {}.",
    "Played games: {}. Recommend a new game for me.",
    "I've played these games: {}.",
    "{} are games I've played. Any recommendations?",
    "History interactions include: {}.",
]
