from autorecipe.genai.GenAIChat import GenAIChatClient
import uuid
import mlflow
from dotenv import load_dotenv
import uuid
import mlflow

from genai.schema import (
    DecodingMethod,
    ModerationHAP,
    ModerationParameters,
    TextGenerationReturnOptions,
)


load_dotenv()
api_key = "pak-whBjdbU__x9iGseK-ZU2q0xbxrI3mwEwgKms9UDBtlg"
api_url = "https://bam-api.res.ibm.com"

ASSET_LIST_complete = [
    "Electrical submersible pump"
]

ASSET_LIST = [
    "Electrical submersible pump",
]


LLMsets = [
    #"thebloke/mixtral-8x7b-instruct-v0-1-gptq",
    #"meta-llama/llama-2-70b-chat",
    "ibm/granite-13b-labrador-rc",
]

final_ans = ""
final_confidence = ""

DEFAULT_CONFIG = {
    "model": LLMsets[0],
    "params": {
        "decoding_method": DecodingMethod.GREEDY,
        "min_new_tokens": 200,
        "max_new_tokens": 2000,  # 1500,
        "stop_sequences": ["(TOKENSTOP)"],
        #"stream": True,
        "return_options": TextGenerationReturnOptions(input_text=False, input_tokens=True),
        "moderations": ModerationParameters(
            hap=ModerationHAP(input=True, output=False, threshold=0.01)
        ),
    },
    "creds": {
        "api_key": "pak-whBjdbU__x9iGseK-ZU2q0xbxrI3mwEwgKms9UDBtlg",
        "api_endpoint": "https://bam-api.res.ibm.com",
    },
    "stream": True,
}

def drop_last_paragraph(ans):
    #
    ans_split = ans.split("\n\n")
    if len(ans_split) > 1:
        return '\n\n'.join(ans_split[:-1])
    return ans

def get_asset_description(iteration=3, asset_class="Electrical submersible pump"):
    """_summary_

    :param iteration: _description_, defaults to 10
    :type iteration: int, optional
    :param asset_class: _description_, defaults to "Electrical submersible pump"
    :type asset_class: str, optional
    """

    SystemPrompt = """
    You are a helpful AI assistant. Given an Industrial asset, generate its description. 
    You can take a look at the following examplers. Output should contain only generate 
    Answer. 

    Question: Describe Wind Turbine Asset and its components.

    Answer: A wind turbine is a tall tower with long, spinning blades that 
    capture the wind's energy.  The wind pushes the blades around, which 
    turns a shaft that connects to a generator. The generator converts the 
    mechanical energy of the spinning shaft into electricity that we can 
    use in our homes and businesses. The main components of a wind turbine include the rotor blades, 
    the hub, the main shaft, the gearbox, the generator, the yaw system, 
    and the control system.

    Question: Describe Substation Electrical Transformer Asset and its components.

    Answer: A substation electrical transformer is a large electrical device 
    that changes the voltage of electricity. It's like a gear on a bike, 
    but instead of changing the speed of the pedals, it changes the power 
    of the electricity.  High-voltage electricity from power plants travels 
    through transmission lines to substations. The transformer steps down 
    the voltage to a safer level for distribution lines, which send the 
    electricity to homes and businesses. The main components of a substation electrical transformer include the core, windings,
    insulation, oil, and cooling system. The core is made up of thin laminations of
    steel, which are stacked together to form the magnetic circuit. The windings are
    the conductors that carry the electrical current, and are insulated from each
    other and the core to prevent short circuits. The insulation is typically made
    of paper or oil-impregnated pressboard, and is used to insulate the windings from
    each other and the core. The oil serves as both a coolant and insulator, and helps
    to prevent the transformer from overheating. The cooling system is used to remove
    the heat generated by the transformer during operation.

    """
    initstep = True
    stateful = False

    for i in range(iteration):
        experiment_name = (
            "MyExperiment_" + asset_class + "_" + str(uuid.uuid4())
        )
        experiment_id = mlflow.create_experiment(experiment_name)

        if initstep:
            mdl = GenAIChatClient(
                name="a",
                description="b",
                skill="c",
                model=LLMsets[0],
                params=DEFAULT_CONFIG["params"],
                system_message=SystemPrompt,
                credentials=DEFAULT_CONFIG["creds"],
                stateful=stateful,
            )

        sentence = (
            "Question: Describe "
            + asset_class
            + " Asset, and its components."
        )
        if i > 0:
            sentence += " \n Generate better solution in terms of completeness."
            #sentence += " \n Generate better solution in terms of readability, accuracy, and completeness."

        ans = mdl.create(
            context=None,
            messages=[{"content": sentence, "role": "user"}],
            experiment_id=experiment_id,
        )
        # ans = 'ans'
        #print("-" * 20)
        #print(sentence)

        experiment_record = {}

        answer = ans.replace("Answer:", "").strip()
        answer = drop_last_paragraph(answer)
        #print(f"Answer: {answer}")
        iteration_count = i + 1
        #print(
        #    f"Asset Class: {asset_class}, iteration: {iteration_count}"
        #)
        #print(f"Answer Length: {str(len(answer))}")

        experiment_record["asset_class"] = asset_class
        experiment_record["iteration_count"] = iteration_count
        experiment_record["answer_length"] = len(answer)
        experiment_record["answer"] = answer

        if not stateful:
            SystemPrompt += (
                "\n\n "
                + sentence
                + "\n\n Answer: "
                + answer
                + "% (TOKENSTOP)\n\n\n"
            )
    return answer

"""    
p_ans = get_asset_description(iteration=10, asset_class="Electrical submersible pump")
print (p_ans)
"""