from generate_failure_locations_from_context_thinking_components import get_components
from generate_failure_locations_from_context_thinking_failure_mode import (
    get_failure_modes,
)
from generate_failure_locations_from_context_thinking_failure_location import (
    get_failure_locations,
)

asset_class = "Battery Charger"

sample_assetdesc = """
 Sure, here's a more comprehensive description of a Battery Charger asset and its components, including the component boundary of the battery charger input breakers:

A battery charger is an industrial asset that is used to charge batteries for various applications such as backup power systems, electric vehicles, and renewable energy systems. The main components of a battery charger include the following:

1. Input Breakers: These are electrical switches that control the flow of electrical current from the power source to the charger. They are designed to protect the charger and the battery from overcurrent and short-circuit conditions. The input breakers are an essential component of the battery charger asset, as they ensure the safe and reliable operation of the charger.
2. DC-DC Converter: This component converts the input voltage and current from the power source to the required voltage and current for charging the battery. It is typically a high-efficiency converter that minimizes energy loss and heat generation. The DC-DC converter is a critical component of the battery charger, as it determines the charging voltage and current that are applied to the battery.
3. Battery Interface: This component connects the charger to the battery and manages the flow of electrical current during charging and discharging. It also monitors the battery's state of charge, voltage, and temperature. The battery interface is a crucial component of the battery charger, as it ensures the safe and efficient transfer of electrical energy between the charger and the battery.
4. Control and Monitoring System: This component manages the operation of the charger and monitors its performance. It receives input from sensors and sends output to actuators to control the charging process. It also provides alarm and warning signals in case of faults or abnormal conditions. The control and monitoring system is a vital component of the battery charger, as it ensures the safe and reliable operation of the charger and provides real-time monitoring of the charging process.
5. Cooling System: This component is responsible for dissipating the heat generated by the charger during operation. It can be a fan, a heat sink, or a liquid cooling system, depending on the size and rating of the charger. The cooling system is an essential component of the battery charger, as it ensures the safe operation of the charger and prevents overheating, which can damage the charger's internal components.
6. Housing and Enclosure: This component protects the charger's internal components from environmental factors such as dust, moisture, and mechanical stress. It also provides a safe and convenient way to install and maintain the charger. The housing and enclosure are important components of the battery charger, as they provide a protective barrier against environmental factors and ensure the safe operation of the charger.
7. Electrical Interconnects: These components connect the charger to the power source, battery, and other peripheral devices. They are designed to handle the electrical current and voltage requirements of the charger and battery. The electrical interconnects are critical components of the battery charger, as they ensure the safe and efficient transfer of electrical energy between the charger and the power source and battery.
8. Insulation and Grounding: These components ensure the safe operation of the charger by providing electrical insulation and grounding between the charger's internal components and the external environment. Proper insulation and grounding are essential for the safe operation of the charger and prevent electrical shock or damage to the charger's internal components. 
"""

model_id = 1  #lamma
model_id = 3 # granite
model_id = 2 # mystral
model_id = 5 # outside mystral

components_str, component_list = get_components(
    asset_class, sample_assetdesc, model_id=model_id
)
print (components_str)
print (component_list)

failuremode_ans = get_failure_modes(components_str, model_id=model_id)
print (failuremode_ans)

failure_locations = get_failure_locations(
    failuremode_ans, model_id=model_id
)
print (failure_locations)
